# Generated by Django 5.0.6 on 2024-05-27 22:13

import karaoke.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=karaoke.models.get_upload_path)),
            ],
        ),
    ]
