# Generated by Django 5.0.6 on 2024-05-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='recording',
            name='audioFile',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\byung\\Desktop\\Auto Okay\\Auto_Okay\\media\\recording.wav'),
        ),
    ]
