# Generated by Django 5.0.4 on 2024-05-16 06:19

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mymodel_audio_file1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='audio_file1',
            field=models.FileField(upload_to=main.models.get_upload_path),
        ),
    ]
